# Generated by Django 5.2.17 on 2026-09-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_galleryphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='pin',
            field=models.CharField(max_length=128),
        ),
    ]
