# Generated by Django 5.2.17 on 2026-09-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
